name: Codecov

on:
  pull_request:

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # main
      - name: Setup Python
        uses: actions/setup-python@5db1cf9a59fb97c40a68accab29236f0da7e94db # main
        with:
          python-version: 3.12
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pytest --cov