name: Codecov

on:
  pull_request:

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # main
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # main
        with:
          python-version: 3.12
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pytest --cov