name: Codecov

on:
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: 3.12
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pytest