name: Codecov

on:
  pull_request:

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # main
      - name: Setup Python
        uses: actions/setup-python@1928ae624dc06094d8c65f021a4700ea8fa56b9d # main
        with:
          python-version: 3.12
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pytest --cov