name: hadolint-dockerfile

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: hadolint
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - id: hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: .Dockerfile
          error_level: 2 # fail on errors
          output_format: tty # output hadolint_output= >> $GITHUB_OUTPUT
          annotate: true


      - name: Dump hadolint output
        env:
          HADOLINT_OUTPUT: ${{ steps.hadolint.outputs.hadolint_output }}
        run: echo "${HADOLINT_OUTPUT}"