name: Lint Dockerfile

on:
  pull_request:
    paths:
      - .Dockerfile

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: hadolint
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: .Dockerfile
          failure-threshold: warning