name: hadolint-dockerfile

on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: hadolint
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .Dockerfile


      #- name: Dump hadolint output
      #  env:
      #    HADOLINT_OUTPUT: ${{ steps.hadolint.outputs.hadolint_output }}
      #  run: echo "${HADOLINT_OUTPUT}"