name: Lint Dockerfile

on:
  pull_request:
    paths:
      - .Dockerfile

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: hadolint
    permissions:
      packages: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .Dockerfile
          failure-threshold: warning