name: 'Test container on PR'
on: [pull_request]

permissions:
  contents: read

jobs:
  run-container-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1

      #- name: Git diff scripts dir
      #  run: |
      #    SCRIPT_DIRECTORY=scripts
      #    CHANGES_SCRIPT_DIR=$(git diff origin/main -- "$SCRIPT_DIRECTORY")
      #    echo "CHANGES_SCRIPT_DIR=$CHANGES_SCRIPT_DIR" >> $GITHUB_ENV

      #- name: Make shell scripts executable
      #  run: chmod +x ${PWD}/scripts/build_test_image.sh && chmod +x ${PWD}/scripts/check_version_was_changed.sh

      - name: git fetch
        run: git fetch origin

      - name: Check that version was changed
        run: ${PWD}/scripts/check_version_was_changed.sh

      - name: Build and smoke test Docker image
        run: ${PWD}/scripts/build_test_image.sh