name: 'Test container on PR'
on: [pull_request]

permissions:
  contents: read

jobs:
  run-container-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@38ecb5b593bf0eb19e335c03f97670f792489a8b # v4.7.0

      #- name: Git diff scripts dir
      #  run: |
      #    SCRIPT_DIRECTORY=scripts
      #    CHANGES_SCRIPT_DIR=$(git diff origin/main -- "$SCRIPT_DIRECTORY")
      #    echo "CHANGES_SCRIPT_DIR=$CHANGES_SCRIPT_DIR" >> $GITHUB_ENV

      #- name: Make shell scripts executable
      #  run: chmod +x ${PWD}/scripts/build_test_image.sh && chmod +x ${PWD}/scripts/check_version_was_changed.sh

      - name: git fetch
        run: git fetch origin

      - name: Check that version was changed
        run: ${PWD}/scripts/check_version_was_changed.sh

      - name: Build and smoke test Docker image
        run: ${PWD}/scripts/build_test_image.sh