name: 'Test container on PR'
on: [pull_request]

permissions:
  contents: read

jobs:
  run-container-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0

      #- name: Git diff scripts dir
      #  run: |
      #    SCRIPT_DIRECTORY=scripts
      #    CHANGES_SCRIPT_DIR=$(git diff origin/main -- "$SCRIPT_DIRECTORY")
      #    echo "CHANGES_SCRIPT_DIR=$CHANGES_SCRIPT_DIR" >> $GITHUB_ENV

      #- name: Make shell scripts executable
      #  run: chmod +x ${PWD}/scripts/build_test_image.sh && chmod +x ${PWD}/scripts/check_version_was_changed.sh

      - name: git fetch
        run: git fetch origin

      - name: Check that version was changed
        run: ${PWD}/scripts/check_version_was_changed.sh

      - name: Build and smoke test Docker image
        run: ${PWD}/scripts/build_test_image.sh