name: 'Test container on PR'
on: [pull_request]

permissions:
  contents: read

jobs:
  container-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0

      - name: Make shell scripts executable
        run: chmod +x ${PWD}/scripts/build_test_image.sh && chmod +x ${PWD}/scripts/check_version_was_changed.sh

      - name: pwd
        run: pwd

      - name: ls
        run: ls

      - name: Check that version was changed
        run: ${PWD}/scripts/check_version_was_changed.sh

      - name: Build and smoke test Docker image
        run: ${PWD}/scripts/build_test_image.sh